using FastSQL.Sync.Core;
using FastSQL.Sync.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace FastSQL.App.UserControls.Previews
{
    /// <summary>
    /// Interaction logic for WPreviewData.xaml
    /// </summary>
    public partial class WPreviewData : Window
    {
        private readonly PreviewDataViewModel viewModel;

        public WPreviewData(PreviewDataViewModel viewModel)
        {
            InitializeComponent();
            DataContext = viewModel;
            this.viewModel = viewModel;
            this.Loaded += WPreviewData_Loaded;
            //dgrData.AutoGeneratingColumn += DgrData_AutoGeneratingColumn;
            //dgrData.AutoGeneratedColumns += DgrData_AutoGeneratedColumns;
        }

        //private void DgrData_AutoGeneratedColumns(object sender, EventArgs e)
        //{
        //    var lastColumn = dgrData.Columns.LastOrDefault();
        //    if (lastColumn != null)
        //    {
        //        lastColumn.Width = new DataGridLength(1, DataGridLengthUnitType.Star);
        //    }   
        //}

        //private void DgrData_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        //{
        //}

        private void WPreviewData_Loaded(object sender, RoutedEventArgs e)
        {
            viewModel.Load();
        }

        public void SetPuller(IPuller puller)
        {
            viewModel.SetPuller(puller);
        }

        public void SetIndex(IIndexModel model)
        {
            viewModel.SetIndex(model);
        }
        
        public void Load()
        {
            viewModel.Load();
        }
    }
}
